// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDZtGxETIcGt-_EKVrLSx_lb_1APt5S7M',
    appId: '1:104262544752:web:213670acabf21e956433b5',
    messagingSenderId: '104262544752',
    projectId: 'e-commerce-flutter-e8176',
    authDomain: 'e-commerce-flutter-e8176.firebaseapp.com',
    storageBucket: 'e-commerce-flutter-e8176.firebasestorage.app',
    measurementId: 'G-MK3JP5LG31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2fge7nkklNoNB-X6TknrAkKf34la2rhk',
    appId: '1:104262544752:android:a4de154bee02fd3c6433b5',
    messagingSenderId: '104262544752',
    projectId: 'e-commerce-flutter-e8176',
    storageBucket: 'e-commerce-flutter-e8176.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0fy22bP4FU6XePc2fNBaArovhp186r2w',
    appId: '1:104262544752:ios:338a4fa0afb95a2d6433b5',
    messagingSenderId: '104262544752',
    projectId: 'e-commerce-flutter-e8176',
    storageBucket: 'e-commerce-flutter-e8176.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0fy22bP4FU6XePc2fNBaArovhp186r2w',
    appId: '1:104262544752:ios:338a4fa0afb95a2d6433b5',
    messagingSenderId: '104262544752',
    projectId: 'e-commerce-flutter-e8176',
    storageBucket: 'e-commerce-flutter-e8176.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDZtGxETIcGt-_EKVrLSx_lb_1APt5S7M',
    appId: '1:104262544752:web:4be03b11ee464cfa6433b5',
    messagingSenderId: '104262544752',
    projectId: 'e-commerce-flutter-e8176',
    authDomain: 'e-commerce-flutter-e8176.firebaseapp.com',
    storageBucket: 'e-commerce-flutter-e8176.firebasestorage.app',
    measurementId: 'G-ENTKW9GB09',
  );
}
